spring:
  application:
    name: spring-grpc-client-security-csrf
  grpc:
    client:
      channels:
        simple:
          address: localhost:9090
logging:
  level:
    org.springframework.security: trace
